[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "open_chat"
version = "0.1.0"
description = "Open Chat Project"
requires-python = ">=3.8" 